### ISSUE TITLE
As a Leadership Team member  in order to keep our list of new projects up to date I want a means to do so.

### ISSUE THREAD

**Issue by adrianz-kainos** [KainosSoftwareLtd/project-dashboard#15]
A user should be able to add a new project, they should be able to set the Title, the location, the description and the phase of the project.

The changes should also be reflected on the website without restarting the whole application. Currently the project's data is loaded only during startup.

**Comment by Rory80Hz** [comment]
Yeah, sounds sensible, on reload any changes should be reflected.
