### ISSUE TITLE
As a Leadership team member responsible for Security in order to track the current status of the project i want a means to do so.

### ISSUE THREAD

**Issue by Rory80Hz** [KainosSoftwareLtd/project-dashboard#21]
It should be possible to capture the current status in terms of Security coverage of the project with a simple indication of health and a link to the write up.

The date and time of the update should be added as well as an indication of the person that added it.

The status should be unknown if it has not been set.

**Comment by adrianz-kainos** [comment]
@Rory80Hz Do we want to keep a history of security statuses? Like in Ryszard's task.
