### ISSUE TITLE
Integrate with CD platform

### ISSUE THREAD

**Issue by Rory80Hz** [KainosSoftwareLtd/project-dashboard#44]
As a team we want our latest changes deployed so we can share them with our users for feedback.

**Given** A pull request is accepted
**When** code is merged to master
**Then** it is deployed to an environment

_Additional Detail_
Currently as this is in Alpha there are zero tests, so deploying to the sandbox is enough.

**Comment by adrianz-kainos** [comment]
We added a pipeline to Heroku. It auto-deploys master to the dev environment.
