### ISSUE TITLE
Create views to support all BU's

### ISSUE THREAD

**Issue by garethwkainos** [KainosSoftwareLtd/project-dashboard#68]
Create a way to toggle what is displayed per BU so that the tool could be used Kainos wide more easily. 

Please include the ability to include internal (Corporate) projects, they too should be delivered to the same high standards.

**Comment by Rory80Hz** [comment]
Absolutely, we'll look into adding this as a feature. For now, this won't prevent users from adding projects, it's likely we'd add this as an additional optional detail for each project and a grouping mechanism...

We'll get input from Delivery / Tech leaders from each BU to see what would make most sense.
