### ISSUE TITLE
Landing Page - Customer Name should prefix customer name

### ISSUE THREAD

**Issue by moomzni** [KainosSoftwareLtd/project-dashboard#80]
Currently we define both a project and customer name but the project name normally contains the customer name anyway.  Hows about the 'display name' is the project name prefixed by customer name.

This means:
 - Project Name: Help with prison vists
 - Customer Name: HMPPS Digital Studio

But is displayed as HMPPS Digital Studio - Help with prison visits

**Comment by Rory80Hz** [comment]
This has been fixed in #83
