### ISSUE TITLE
Project description input box

### ISSUE THREAD

**Issue by moomzni** [KainosSoftwareLtd/project-dashboard#81]
The project description input box could be made a little bigger; its currently tiny :)
![Screen Shot 2017-08-04 at 16.08.11.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59847db246de74001f14e238/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6454f76b7191a379e90c2b59415e4fbe5d4a1f06a3a3dc78e2a436628f540fe8853c0c7dc46f18a5ba821deb01ba76884680bfbf9850d2aa6c7bb3d4d216744b470a83ed5e34aa984ec859fe4ee84e55a01a3163f43b.png)

**Comment by Rory80Hz** [comment]
Closed by #96
