### ISSUE TITLE
Project history to include service milestones

### ISSUE THREAD

**Issue by moomzni** [KainosSoftwareLtd/project-dashboard#82]
I'd like some way of identifying customer/service milestones in the project history in addition to alpha/beta/live.  As an example I'd like to indicate when customers are onboarded to the Home Office - Digitise Store and View project.

**Comment by Rory80Hz** [comment]
Research needed into whether Alpha/Beta/Live is actually useful for us, or whether we should move to different model based on milestones.

Perhaps, milestones are separate to phases? Within Beta/Live, milestones could be recorded as unique events?

**Comment by Rory80Hz** [comment]
Closing for now, we are unlikely to add this in at the moment.
