### ISSUE TITLE
Link to project health

### ISSUE THREAD

**Issue by moomzni** [KainosSoftwareLtd/project-dashboard#84]
The navigation for viewing the project health status updates should be much clearer.  Presently it isn't all that intuitive.

I would recommend:
- Renaming Project Overall Health -> Health
- Add a link beside this for 'view details'
- Change the display to present health information as a table
- List the overall health at the top (in a row colorised as present e.g. green for good)
- List the last 4 health updates (not including the overall health if relevant) in the next 4 spaces

![Screen Shot 2017-08-18 at 10.12.59.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59847db246de74001f14e238/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6455fb6b7191a379ef0c2a53415a47be5d4a1f06a3a3dc78e2a436628f540fe8853c0c7dc46f18a5ba821deb01ba76884680bfbf9850d2aa6c7bb3d4d216744b470a83ed5e3ca09c41c95df648e14952a213376ae5742431.png)

**Comment by Rory80Hz** [comment]
Closed by #94 

This was updated to reflect project support need in terms of senior people, and the links to detail reworked as part of this.

If this doesn't work, open a new issue!
