### ISSUE TITLE
Flagging internal risks so prominently makes me want to avoid opening the project dashboard on customer site

### ISSUE THREAD

**Issue by alirawashdeh** [KainosSoftwareLtd/project-dashboard#86]
Maybe move risks into a collapsible section, make the text less IN YOUR FACE, or move it to the bottom.

**Comment by alirawashdeh** [comment]
![pic.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d5f17e42592500138f4bda/125516c66e82c728ace21e0d46f89d9961cec1b99de6b546a749b2ce6b137f277c00a22829d7e171e6102b530b5f4efa42515a4dffeb9539e4e76224d50152a7842f4d7ed43c16a6b9871fb800b323884881b3ba835e8d.png)
Screenshot attached (i've blocked out the text)

**Comment by Rory80Hz** [comment]
Thanks Ali, we'll have a look at how to make this less in your face, release and ask for feedback.

**Comment by Rory80Hz** [comment]
We'll lower the profile of the latest health update, and build a risk specific 'dashboard' view as there are different user needs trying to be met by one 'mega-view'

**Comment by Rory80Hz** [comment]
Fixed by #94
