### ISSUE TITLE
Denote technical owner

### ISSUE THREAD

**Issue by chriscartin** [KainosSoftwareLtd/project-dashboard#87]
As a sales person I want to be see who the 'main' technical owner and sales owner are so I know who to contact further queries about the of the project

**Comment by Rory80Hz** [comment]
This is do-able now without any changes, you can type the role for the person when adding them to the team. I think adding boolean values to this over-complicate the model, and, isn't very evolve-able, we have a story in the backlog to indicate someone is the assurance owner also, we could conceivably have other 'ownerships'  for a person.

**Comment by Rory80Hz** [comment]
Closing, not going to do anything with this.
