### ISSUE TITLE
Add/View Sector, Department and Agency

### ISSUE THREAD

**Issue by chriscartin** [KainosSoftwareLtd/project-dashboard#88]
As a sales person I want to see the Sector, Department and Agency for a particular project so I can easily identify projects for a specific client to reference and draw upon

**Comment by Rory80Hz** [comment]
What are the values we would use for the fields above?

I'm guessing for Sector is Public or Private, the Department and Agency is likely free text? How does this square with Private sector customers? They wouldn't have the same model?

**Comment by Rory80Hz** [comment]
As discussed, lets go with Public and Private as sector values, then free text for the rest.
