### ISSUE TITLE
Add/View Exemplar, Case Study available and theme

### ISSUE THREAD

**Issue by chriscartin** [KainosSoftwareLtd/project-dashboard#89]
As a sales person I want to see further attributes for a project so that I can identify projects of a certain nature or theme to reference or draw upon

**Comment by RichardEustace** [comment]
More details around Theme to be provided.

**Comment by Rory80Hz** [comment]
This feels similar to the story around themes...when we are talking about referenceability, material that's useful should be added to the links associated with a project, possibly using the same tagging mechanism as the criteria story would let us find those deliveries that match up.
