### ISSUE TITLE
View all projects with specific criteria

### ISSUE THREAD

**Issue by chriscartin** [KainosSoftwareLtd/project-dashboard#90]
As a sales person I want to be able to view projects with specific criteria so I can cite the details to potential customers

**Comment by chriscartin** [comment]
Quite a bit of refining needed for this story as there are many ways to achieve this. To be discussed with dev team when it's prioritised.

**Comment by Rory80Hz** [comment]
Can we list the criteria we think we'd like to add? I think we could solve this using tags, rather than checkboxes...it's more flexible. More work to implement, but it would mean we can add and remove 'categorisations' as we need.

How to view then could be based on a search across tags...
